### PR TITLE
Add brew-completions plugin

### PR DESCRIPTION
**Pull request by laughedelic**
I just published a plugin with improved Homebrew completions for Fish: https://github.com/laughedelic/brew-completions

(I know that I have permissions to merge anything here, but I still think it should be done by somebody else)

### CODE REVIEW

**Comment by laughedelic** [comment]
Wow! That was fast! ⚡️

**Comment by jbucaran** [comment]
@laughedelic By all means do merge stuff next time! I don't have time to develop fisherman much anymore.

**Comment by laughedelic** [comment]
OK.
Is it just lack of time or interest as well?

**Comment by jbucaran** [comment]
Definitely lack of time. Work and [hyperapp](https://github.com/hyperapp/hyperapp) are taking most of my time now. 

But, I also switched to [fin](https://github.com/fisherman/fin), since I prefer the approach there and the fact that installs/uninstalls are 100% reliable due to its immutable architecture.

I tried to push for merging that with fisherman, but it never happened, remember?

When I get more time I plan to rewrite fin and publish something new, completely separated from fisherman & oh-my-fush.

**Comment by laughedelic** [comment]
OK, I see. 
fin is nice, but I think it's too minimalistic to ever become mainstream/popular..

**Pull request merged**
