### PR TITLE
Add exenv and nodenv to the index

### PR DESCRIPTION
**Pull request by createdbypete**
Add exenv and nodenv to the index after discussion in issue below. 🎉 

Closes https://github.com/fisherman/rbenv/issues/3

### CODE REVIEW

**Comment by createdbypete** [comment]
Sorry just realised I mess up the ordering and broke the build. How do you even alphabet!? 😭

**Comment by jbucaran** [comment]
I used to break it all the time. Luckily @jethrokuan knows his ABCs pretty well and made the CI autocheck. 😆

**Comment by createdbypete** [comment]
Happy to fix in another PR? Don't like leaving a failure 😊

**Comment by jethrokuan** [comment]
Let's not forget the people who really cleaned up my mess :P @sijad

**Comment by jbucaran** [comment]
So true! 🙇 @sijad 👏

**Pull request merged**
