### PR TITLE
Add todo.fish

### PR DESCRIPTION
**Pull request by jaredculp**

### CODE REVIEW

**Comment by jethrokuan** [comment]
Could you kindly reorder your item so that CI passes?

**Comment by jaredculp** [comment]
Yep just pushed up a new change

**Comment by jethrokuan** [comment]
you missed an author row.

**Comment by jaredculp** [comment]
Heh guess it would help if I could read

**Comment by jethrokuan** [comment]
:+1: Welcome to the club!

**Comment by jaredculp** [comment]
Thanks for the quick merge!

**Pull request merged**
