### PR TITLE
Add externl/fish-symnav

### PR DESCRIPTION
**Pull request by externl**

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
Thanks!

**Comment by externl** [comment]
Wow, that was fast. Thanks!

**Comment by JorgeBucaran** [comment]
@externl Do you know why the build failed? 🤔

**Comment by externl** [comment]
Hmm... I guess because I'm currently missing unit tests?

**Comment by externl** [comment]
```
ok 133 embark
ok 134 https://github.com/knarka/embark
ok 135 Slightly piratical shell bookmarks
not ok 136 bookmarks navigation cd jump find
   ---
   Too many tags
   ...
```

**Pull request merged**
