### PR TITLE
Added nvm to the list

### PR DESCRIPTION
**Pull request by FabioAntunes**

### CODE REVIEW

**Comment by jethrokuan** [comment]
the nvm wrapper is deprecated in favour of [fin](https://github.com/fisherman/fin).

**Comment by bucaran** [comment]
@jethrokuan This is not omf/nvm, but @FabioAntunes's own nvm wrapper! :)

**Comment by FabioAntunes** [comment]
@jethrokuan This is a small wrapper around nvm, because some people due to company rules and cosmic stuff still need to use nvm

**Comment by jethrokuan** [comment]
Ah I thought it was the nvm wrapper @bucaran created which was then renamed

**Comment by bucaran** [comment]
All clear then.

**Pull request merged**
