### PR TITLE
add in colored-man-pages plugin

### PR DESCRIPTION
**Pull request by patrickf3139**

### CODE REVIEW

**Comment by jethrokuan** [comment]
I think you need to append your github handle to that. Also, on your readme, to access vanilla `man` on fish it's still easier to just use `command man __` 😄

**Comment by patrickf3139** [comment]
Thanks for the two tips Jethro! Done and done 😄

**Comment by jorgebucaran** [comment]
@patrickf3139 I don't mind the Oh My Fish! logo in your README, but could you not say "Oh My Fish plugin" and use "fish-shell plugin" or "plugin for fish-shell" instead?

**Comment by jorgebucaran** [comment]
BTW this is really useful!

**Comment by jorgebucaran** [comment]
Also, I don't understand the purpose of the `man.fish` in the root directory.

**Comment by patrickf3139** [comment]
@jorgebucaran Thank you so much for your suggestions. Free code reviews! Done and done!

**Comment by jorgebucaran** [comment]
LGTM

**Comment by patrickf3139** [comment]
Woohoo thanks!

**Pull request merged**
