### PR TITLE
Added fish_logo plugin

### PR DESCRIPTION
**Pull request by laughedelic**
- https://github.com/laughedelic/fish_logo

### CODE REVIEW

**Comment by laughedelic** [comment]
It complains about sorting "/ I though that underscore goes first, doesn't it?

**Comment by laughedelic** [comment]
I guess, I could. I just don't really like that the org is kind of a mix of plugins with other things related to fisherman.. 
Anyway, to be searchable online, it has to be in the index, right? So what's the problem with Travis here? Shoul I put it between `fishtape` and `flash`?

**Comment by brj** [comment]
Probably.

**Comment by brj** [comment]
Keep in mind that the index is still here just for historical reasons. It may not be in the future. Ideally, the online search would just list the contents under fisherman org as well as other orgs of plugins, such as oh-my-fish. 

Adding plugins to the org makes it easier to users to discover contents.

**Comment by wk** [comment]
@laughedelic I, too, maintain a fish function (originally for omf, but which I'd like to make easily available for installation with fisherman) which I'd like to keep in my own repository rather than under the `fisherman` org.

The most obvious way to do this would be to simply parse the same Index used for the web-based search on [fisherman.sh](http://fisherman.sh). I've opened issue fisherman/fisherman#308 for this.

@brj however brings up a valid point - maintaining an alphabetic text file of plugins might not be a great way to go forward overall. The player-based approach of indexing the `oh-my-fish` and `fisherman` repositories is incredibly simple and elegant, however, not conductive to this goal. It would be great if we could find a low-touch approach that's both elegant and doesn't necessitate including all the plugins under one org.

One solution that comes to [mind](https://github.com/wk/plugin-ssh-term-helper/issues/1#issuecomment-223802549) involves using a single repository with git remotes. It's probably also not ideal.

Thoughts?

**Comment by wk** [comment]
Another idea is perhaps to create a single 'base' plugin repository under fisherman, e.g. `fisherman/plugin-scaffold` and `fisherman/theme-scaffold` with dummy `README.md` or `LICENSE` files, and use the Github API to list all [forks](https://developer.github.com/v3/repos/forks/#list-forks) of these repositories - then include them in the local Index as just another form of player.

This provides some amount of elegance and simplicity, but requires all plugins to reside within Github.

**Comment by brj** [comment]
https://github.com/fisherman/fishkit

**Comment by wk** [comment]
For this purpose, having a *scaffold generator* and having a *scaffold* is not quite the same; while tracking forks of a specific scaffold would be sensible in the above context, forking the scaffold generator itself probably does not.

The current Index file based approach seems to come out on top as the most versatile.

**Comment by laughedelic** [comment]
> Keep in mind that the index is still here just for historical reasons. It may not be in the future. Ideally, the online search would list the repos under fisherman org as well as other orgs of plugins, namely oh-my-fish at the moment, but there may be others in the future, who knows.

I think that manually curated index or something equivalent is unavoidable. But I think that most things can be automated, so that it will be easy **both** for fisherman and for plugin developers to work with it.

Plugin developers are required to do something to make their plugins discoverable for users anyway. But I think there will be always some plugins not in the org. Putting everything in the same org and querying it with github API is just the easy way for fisherman.

**Pull request merged**
