### PR TITLE
Add plugin: fisherman/done

### PR DESCRIPTION
**Pull request by aristidesfl**
https://github.com/fisherman/done

### CODE REVIEW

**Comment by laughedelic** [comment]
When I install it, it resets my left prompt 😐

**Comment by aristidesfl** [comment]
@laughedelic sorry about that. Did you install manually or with fisherman? Does fish support multiple fish_right_prompt functions?

**Comment by laughedelic** [comment]
> Did you install manually or with fisherman?

With fisherman.

> Does fish support multiple fish_right_prompt functions?

I don't think so. But just overriding the right prompt would be fine. The problem is that it resets the left one..

**Comment by aristidesfl** [comment]
Oh didn't realise that. it sounds strange. Maybe fisherman has something to do with that. @jbucaran ?

**Comment by jbucaran** [comment]
@aristidesfl I checked your plugin and it looks fine. Hmm what fisherman version are you running?

**Comment by aristidesfl** [comment]
It also installs fine for me. 
```
$ fisher --version
fisherman version 2.11.0 ~/.config/fish/functions/fisher.fish
```
@laughedelic what version are you using?

**Comment by laughedelic** [comment]
Same

```
> fisher --version
fisherman version 2.11.0 ~/.config/fish/functions/fisher.fish
>  fisher ls
@ ec2ls			  autojump		  get			  grc			  last_job_id		  pwd_info		  spin
@ fish			  fish_logo		  getopts		  host_info		  menu			  pwd_is_home
* nitro			  fishkit		  git_util		  humanize_duration	  pisces		  segment
```

Can it be the problem of the theme I'm using? It's [nitro](https://github.com/fisherman/nitro).

**Comment by aristidesfl** [comment]
@laughedelic what does `~/config/fish/functions/fish_prompt.fish` look like afterwards? And is it a symlink? And could you reproduce the issue a second time?

**Comment by laughedelic** [comment]
It gets removed 😆 

```
~/dev  ll ~/.config/fish/functions/fish*_prompt.fish
fish_prompt.fish -> /Users/laughedelic/.config/fisherman/nitro/fish_prompt.fish
fish_right_prompt.fish -> /Users/laughedelic/.config/fisherman/nitro/fish_right_prompt.fish

~/dev  fisher install done
Installing 1 plugin/s
OK Copy done
Done in 472ms

laughedelic@MacBook ~/dev> ll ~/.config/fish/functions/fish*_prompt.fish
fish_right_prompt.fish -> /Users/laughedelic/.config/fisherman/done/fish_right_prompt.fish

laughedelic@MacBook ~/dev> fisher ls
@ ec2ls		* done		  fish_logo	  get		  grc		  pisces
@ fish		  autojump	  fishkit	  getopts	  menu		  spin

laughedelic@MacBook ~/dev> fisher install nitro
Installing 1 plugin/s
OK Copy nitro
Installing 7 dependencies
OK Copy segment
OK Copy git_util
OK Copy pwd_is_home
OK Copy pwd_info
OK Copy host_info
OK Copy last_job_id
OK Copy humanize_duration
Done in 715ms

~/dev  fisher ls                                                                                                                                                          (841ms)
@ ec2ls			  autojump		  get			  grc			  last_job_id		  pwd_info		  spin
@ fish			  fish_logo		  getopts		  host_info		  menu			  pwd_is_home
* nitro			  fishkit		  git_util		  humanize_duration	  pisces		  segment
```

The prompt with this funny square is `nitro`.

**Comment by jbucaran** [comment]
Ah, this must be a bug. Someone please file it in the fisherman issue tracker.

**Comment by aristidesfl** [comment]
Just fyi: fisherman/done no longer uses `fish_left_prompt.fish`

**Comment by jbucaran** [comment]
LGTM!

**Comment by aristidesfl** [comment]
@laughedelic could please test v1.0.0 when you have time? It's supposed to support Linux and macOS and no longer uses a list of excluded commands.

If it works fine I would finally merge this into the index.

**Comment by laughedelic** [comment]
@aristidesfl it works fine! thanks for a personal notification ")

**Comment by jbucaran** [comment]
Finally! 🎉

**Pull request merged**
